### ISSUE TITLE
No merge sort

### ISSUE THREAD

**Issue by HomeboxJim** [humanwhocodes/computer-science-in-javascript#37]
I came here from this merge sort post: https://www.nczonline.net/blog/2012/10/02/computer-science-and-javascript-merge-sort/

But I don't see any merge sort examples here. :(

**Comment by mschultz4** [comment]
did you look in the [algorithms/sorting](https://github.com/nzakas/computer-science-in-javascript/tree/master/algorithms/sorting) directory?
